mysql:
  username: root
  password: password
  hostname: localhost
  database: servermain_db
  port: 3306
worlds:
  - world
max-bounty: 1337
spree:
  min-kills: 3
  messages:
  - '3>&b{name} &6is on a killing spree! &7({spree}:0)'
  - '5>&b{name} &6is dominating! &7({spree}:0)'
  - '7>&b{name} &6is on a rampage! &7({spree}:0)'
  - '10>&b{name} &6is &aLEGENDARY! &7({spree}:0)'
  - '15>&b{name} &6is &dGODLIKE! &7({spree}:0)'
  - '25>&b{name} &6is a &dGOD! &7({spree}:0)'
  ended-message: '&b{name} &7({spree}:0) &6has lost their spree!'
  bounty-increment: 8
default-bounty: 10
prize:
  winner-tags:
  - '&b???'
  - '&b??'
  - '&b?'
  - '&7*****'
  - '&7****'
  - '&7***'
  - '&7**'
  - '&7*'
  winner-titles:
  - '&7[&bGod&7]'
  - '&7[&bAngel&7]'
  - '&7[&bHoly&7]'
top:
  - ''