CREATE TABLE svns_players(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL, uuid BINARY(16) NOT NULL UNIQUE, INDEX uuid_i(uuid)) ENGINE=InnoDB;
CREATE TABLE svns_record(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL, player1 INT UNSIGNED NOT NULL UNIQUE,
  player2 INT UNSIGNED UNIQUE NOT NULL, kills INT UNSIGNED NOT NULL, deaths INT UNSIGNED NOT NULL,
  CONSTRAINT FOREIGN KEY(player1) REFERENCES svns_players(id) ON DELETE CASCADE, CONSTRAINT FOREIGN KEY(player2) REFERENCES
  svns_players(id) ON DELETE CASCADE, CONSTRAINT UNIQUE CLUSTERED(player1, player2)) ENGINE=InnoDB;
CREATE TABLE svns_skill(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL, player INT UNSIGNED NOT NULL UNIQUE, skill REAL NOT NULL,
  CONSTRAINT FOREIGN KEY(player) REFERENCES svns_players(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE svns_rank(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL, player INT UNSIGNED NOT NULL UNIQUE, rank INT UNSIGNED NOT NULL,
  CONSTRAINT FOREIGN KEY(player) REFERENCES svns_players(id) ON DELETE CASCADE) ENGINE=InnoDB;
