name: 777
main: net.rocketeer.sevens.SevensPlugin
version: 0.1.0
depend: [WorldGuard,ProtocolLib]
commands:
  score:
    description: Shows your current score
    usage: /score [player name]
    permission: sevens.cmd.score
    permission-message: You don't have permission to do this!
  scoretop:
    description: Lists high score table
    usage: /scoretop [page number]
    permission: sevens.cmd.scoretop
    permission-message: You don't have permission to do this!
  bounty:
    description: Shows your current bounty or adds bounty to other people
    usage: /bounty [add [player name] bounty]
    permission: sevens.cmd.bounty
    permission-message: You don't have permission to do this!
  spree:
    description: Shows your current spree
    usage: /spree
    permission: sevens.cmd.spree
    permission-message: You don't have permission to do this!
  scoreresetall:
    description: New month of bending. DO NOT USE IF YOU DON'T KNOW WHAT IT DOES
    usage: /scoreresetall
    permission: sevens.admin
    permission-message: You don't have permission to do this!
  rank:
    description: Shows your current rank
    usage: /rank [player name]
    permission: sevens.cmd.rank
    permission-message: You don't have permission to do this!
  ranktop:
    description: Lists highest ranking players
    usage: /ranktop [page number]
    permission: sevens.cmd.ranktop
    permission-message: You don't have permission to do this!