name: 777
main: net.rocketeer.sevens.SevensPlugin
version: 0.0.1
depend: [WorldEdit,WorldGuard,ProtocolLib]
commands:
  ttt:
    description: test
    usage: test
    permission: test
    permission-message: test
  score:
    description: Shows your current score
    usage: /score
    permission: sevens.cmd.score
    permission-message: You don't have permission to do this!
  scoretop:
    description: Lists high score table
    usage: /scoretop [page number]
    permission: sevens.cmd.scoretop
    permission-message: You don't have permission to do this!